# Generated by Django 5.2.4 on 2026-07-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='avatar',
            field=models.CharField(blank=True, default='avatar 1.gif', max_length=100, null=True),
        ),
    ]
