# Generated by Django 5.2.4 on 2026-07-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes_api', '0002_colaborador_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='area',
            field=models.CharField(choices=[('Industria', 'Industria'), ('Mineria', 'Minería'), ('Mantenimiento', 'Mantenimiento'), ('Petroquimica', 'Petroquímica'), ('Seguridad Maquinaria', 'Seguridad de Maquinaria'), ('Administracion', 'Administración'), ('Contabilidad', 'Contabilidad'), ('Recursos Humanos', 'Recursos Humanos'), ('Gerencia General', 'Gerencia General'), ('SIG HESQ', 'SIG. HESQ'), ('TI', 'Tecnologías de la Información (TI)'), ('Comercial', 'Comercial'), ('Logistica Almacen', 'Logística - Almacén')], max_length=50),
        ),
    ]
