# Generated by Django 5.2.4 on 2026-07-17 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes_api', '0003_alter_colaborador_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='intentoquiz',
            name='feedback_capacitacion_score',
            field=models.IntegerField(blank=True, help_text='Calificación de la exposición (1-5)', null=True),
        ),
        migrations.AddField(
            model_name='intentoquiz',
            name='feedback_comentarios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intentoquiz',
            name='feedback_preguntas_score',
            field=models.IntegerField(blank=True, help_text='Calificación de las preguntas (1-5)', null=True),
        ),
    ]
