# Generated by Django 5.2.4 on 2026-07-17 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes_api', '0004_intentoquiz_feedback_capacitacion_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='puntos',
            field=models.IntegerField(default=1),
        ),
    ]
