# Generated by Django 5.2.4 on 2026-07-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes_api', '0005_alter_pregunta_puntos'),
    ]

    operations = [
        migrations.AddField(
            model_name='intentoquiz',
            name='feedback_aplicacion',
            field=models.CharField(blank=True, help_text='Aplicación del conocimiento', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='intentoquiz',
            name='feedback_capacitador_score',
            field=models.IntegerField(blank=True, help_text='Capacitador (1-5)', null=True),
        ),
        migrations.AddField(
            model_name='intentoquiz',
            name='feedback_comprension_score',
            field=models.IntegerField(blank=True, help_text='Comprensión (1-5)', null=True),
        ),
        migrations.AddField(
            model_name='intentoquiz',
            name='feedback_conexion_score',
            field=models.IntegerField(blank=True, help_text='Medio de Conexión (1-5)', null=True),
        ),
        migrations.AddField(
            model_name='intentoquiz',
            name='feedback_expectativas',
            field=models.CharField(blank=True, help_text='Cumplió expectativas (Si/No)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='intentoquiz',
            name='feedback_materiales_score',
            field=models.IntegerField(blank=True, help_text='Materiales (1-5)', null=True),
        ),
        migrations.AddField(
            model_name='intentoquiz',
            name='feedback_tema_score',
            field=models.IntegerField(blank=True, help_text='Tema (1-5)', null=True),
        ),
    ]
