# Generated by Django 5.2.4 on 2026-07-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes_api', '0006_intentoquiz_feedback_aplicacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='correo',
            field=models.EmailField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
