# Generated by Django 5.2.4 on 2026-07-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes_api', '0007_colaborador_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='imagen',
            field=models.TextField(blank=True, help_text='URL o Data URL (base64) de la imagen de la pregunta', null=True),
        ),
    ]
